### ISSUE TITLE
Development TODO v0.1.0

### ISSUE THREAD

**Issue by SeanChao** [SeanChao/mirror-cache#1]
## Features:

- [x] #2
	- [x] #3
	- [x] #10
- [x] #4
- [x] #7
- [x] #15
- [x] #16

## Optimizations:

- [x] #24
- [x] #5
- [x] #8
- [x] #26
- [x] #25
- [x] #13

## Tests & Bug fixes & More:

- [x] #29
- [x] #30
- [x] #31
- [x] #28
- [x] #17
- [x] #18
- [x] PyPI index page upstream rewrite (the replaced URL should be set from the client's perspective)
- [x] Better path resolving method (handling prefix slash better)
- [x] Dockerfile support
- [x] Anaconda link in `README.md`
- [x] update example config file, remove unused settings (rule.target)
